name: CommandBlocker
version: 1.8
main: it.chiarchiaooo.commandblocker.Main
api-version: 1.19
authors: [ Chiarchiaooo ]
description: CommandBlocker 1.18x
softdepend: [PlaceholderAPI]

commands:
  cmdblock:
    description: Main Command

permissions:
  cmdblock.bypass.*:
    description: General bypass permission
  cmdblock.bypass.<command>:
    description: Single command bypass permission
  cmdblock.reload:
    description: Reload plugin config
  cmdblock.restart:
    description: Forcely restart plugin